config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :suggestions do
		resources :votes
  	member do
			post "completed"
			post "incomplete"
		end
		collection do
			get "all_completed"
			get "all_suggested"
			get "all_banned"
		end
  end

  root :to => 'homepage#index'
  get "initial_setup" => "homepage#initial_setup"

  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "homepage#new", :as => "sign_up"
	get "dashboard" => "homepage#dashboard", :as => "dashboard"
	get "blog" => "homepage#blog", :as => "blog"
	resources :accounts

  namespace :admin do
    get "homepage" => "homepage#index"
		resources :cores
		resources :rewards
    resources :supporter_levels do
    	member do
    		get "rewards"
    	end
    end
		resources :users
		resources :posts do
			member do
				post "publish"
			end
		end
  end
  resources :password_resets
end

app/models/supporter_level.rb
class SupporterLevel < ApplicationRecord
  has_many :users
	validates :name, :amount, :description, presence: true
	has_many_attached :rewards
	has_many :subscriptions
end

app/controllers/admin/supporter_levels_controller.rb
class Admin::SupporterLevelsController < ApplicationController
	before_action :admins_only
  before_action :set_supporter_level, only: [:show, :edit, :update, :destroy, :rewards]

  # GET /supporter_levels
  # GET /supporter_levels.json
  def index
    @supporter_levels = SupporterLevel.all
  end

  # GET /supporter_levels/1
  # GET /supporter_levels/1.json
  def show
  end

  # GET /supporter_levels/new
  def new
    @supporter_level = SupporterLevel.new
  end

  # GET /supporter_levels/1/edit
  def edit
  end

  # POST /supporter_levels
  # POST /supporter_levels.json
  def create
    @supporter_level = SupporterLevel.new(supporter_level_params)

    respond_to do |format|
      if @supporter_level.save
        format.html { redirect_to admin_homepage_path, notice: 'Supporter level was successfully created.' }
        format.json { render :show, status: :created, location: @supporter_level }
      else
        format.html { render :new }
        format.json { render json: @supporter_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supporter_levels/1
  # PATCH/PUT /supporter_levels/1.json
  def update
		if @supporter_level.update(supporter_level_params)
	    if params[:supporter_level][:rewards].present?
	      params[:supporter_level][:rewards].each do |reward|
	        @supporter_level.rewards.attach(reward)
	      end
	    end
	    flash[:success] = 'Updated!'
			redirect_to admin_supporter_level_path(@supporter_level)
	  else
	    flash[:error] = 'Not updated'
	    redirect_to admin_supporter_level_path(@supporter_level)
	  end
  end

  # DELETE /supporter_levels/1
  # DELETE /supporter_levels/1.json
  def destroy
    @supporter_level.destroy
    respond_to do |format|
      format.html { redirect_to admin_homepage_path, notice: 'Supporter level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def rewards

	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supporter_level
      @supporter_level = SupporterLevel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supporter_level_params
      params.require(:supporter_level).permit(:name, :amount, :description, :stripe_plan_name, :paypal_plan_name)
    end
end

app/helpers/supporter_levels_helper.rb
module SupporterLevelsHelper
end

app/views/admin/supporter_levels/_form.html.erb
<%= form_with(model: [:admin, @supporter_level]) do |form| %>
  <% if @supporter_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supporter_level.errors.count, "error") %> prohibited this supporter_level from being saved:</h2>

      <ul>
        <% @supporter_level.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
	<div class="col-md-3">
		<div class="field form-group">
	    <%= form.label :name %>
	    <%= form.text_field :name, class: "form-control" %>
	  </div>
	</div>
</div>
<div class="row">
	<div class="col-md-3">
		<div class="field form-group">
	    <%= form.label :amount %>
	    <%= form.text_field :amount, class: "form-control" %>
	  </div>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="field form-group">
	    <%= form.label :description %>
	    <%= form.text_area :description, class: "form-control" %>
	  </div>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<div class="field form-group">
	    <%= form.label :stripe_plan_name %>
	    <%= form.text_field :stripe_plan_name, class: "form-control" %>
			<small id="stripe_plan_nameHelpBlock" class="form-text text-muted">
			  This is the unique identifier generated in the stripe dashboard, just copy and past it from there.
			</small>
	  </div>
	</div>
</div>
<div class="row">
	<div class="col-md-3">
		<div class="actions">
	    <%= form.submit class: "btn btn-primary" %>
	  </div>
	</div>
</div>



<% end %>

app/views/admin/supporter_levels/edit.html.erb
<h2>Editing Supporter Level</h2>

<%= render 'form', supporter_level: @supporter_level %>

<br>

<%= link_to 'Show', admin_supporter_level_path(@supporter_level) %> |
<%= link_to "Add rewards", rewards_admin_supporter_level_path(@supporter_level) %> |
<%= link_to 'Back', :back %>

app/views/admin/supporter_levels/index.html.erb
<br>
<h2>Supporter Levels</h2>
<div class="row">
	<div class="col-md-12">
		Please use these screens to create and edit your supporter levels including setting the base rate for the supporter level. You can then use the rewards screens to bulk upload rewards to multiple supporter levels. If on the other hand you just want to add rewards to one supporter level you can do that below.
	</div>
</div>

<div class="row">
	<% @supporter_levels.each do |supporter_level| %>
		<div class="col-md-4 supporter-level-containers">
			<h3><%= supporter_level.name %> @ <%= number_to_currency(supporter_level.amount, :unit => "£") %></h3>
			<h4><%= supporter_level.users.count %></h4>
			Supporters at this level
			<br>
			<%= link_to 'Edit', edit_admin_supporter_level_path(supporter_level) %> | <%= link_to "Add rewards", rewards_admin_supporter_level_path(supporter_level) %>
			<br>
		</div>
	<% end %>
</div>

<br>

<%= link_to 'New Supporter Level', new_admin_supporter_level_path %>

app/views/admin/supporter_levels/new.html.erb
<h2>New Supporter Level</h2>

<%= render 'form', admin_supporter_level: @supporter_level %>

<br>

<%= link_to 'Back', admin_homepage_path %>

app/views/admin/supporter_levels/rewards.html.erb
<br>
<h2>Add rewards to <%= @supporter_level.name %></h2>
<p>
Use the uploader below to add rewards to just this supporter level. Remember if you want to add rewards to multiple groups then you can do so by following the rewards link in the navbar!
</p>

<p>
The app is currently only accepting videos as mp4 files and images as jpg or png files.
</p>


<%= form_with(model: [:admin, @supporter_level]) do |form| %>
  <% if @supporter_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supporter_level.errors.count, "error") %> prohibited this supporter_level from being saved:</h2>

      <ul>
        <% @supporter_level.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
	<div class="col-md-6">
		<div class="input-group mb-3">
		  <div class="input-group-prepend">
		    <span class="input-group-text" id="inputGroupFileAddon01">Upload Reward</span>
		  </div>
		  <div class="custom-file">
				<%= form.file_field :rewards, multiple: true, class: "custom-file-input", id: "inputGroupFile01" %>
		    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
		  </div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-3">
		<div class="actions">
	    <%= form.submit "Add Rewards", class: "btn btn-primary" %>
	  </div>
	</div>
</div>
<br>
<%= link_to 'Show', admin_supporter_level_path(@supporter_level) %> | <%= link_to "Back", :back %>
<% end %>

app/views/admin/supporter_levels/show.html.erb
<br>
<div class="row justify-content-md-center">
	<div class="col-md-4 supporter-level-containers">
		<h3><%= @supporter_level.name %> @ <%= number_to_currency(@supporter_level.amount, :unit => "£") %></h3>
		<h4><%= @supporter_level.users.count %></h4>
		Supporters at this level
		<br>
		<%= link_to 'Edit', edit_admin_supporter_level_path(@supporter_level) %> | <%= link_to 'Back', :back %> | <%= link_to "Add rewards", rewards_admin_supporter_level_path(@supporter_level) %>
	</div>
</div>
<br>
<div class="row">
	<div class="col-md-6">
		<h3>Current <%= @supporter_level.name %> Level Rewards</h3>
		<p>There are currently <%= @supporter_level.rewards.count %> <%= (@supporter_level.rewards.count) == 1 ? 'reward' : 'rewards'%></p>
	</div>
</div>
<div class="row">
	<% @supporter_level.rewards.each do |reward| %>
		<% if reward.content_type == "video/mp4" then %>
			<div class="col-md-6 frame">
				<%= video_tag(url_for(reward), :controls => true, class: "reward-image") %>
			</div>
		<% elsif reward.content_type == "image/png" || "image/jpg" then %>
			<div class="col-md-6 frame">
				<span class="helper"></span>
				<%= image_tag reward, class: "reward-image" %>
			</div>
		<% end %>
	<% end %>
</div>