config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :suggestions do
		resources :votes
  	member do
			post "completed"
			post "incomplete"
		end
		collection do
			get "all_completed"
			get "all_suggested"
			get "all_banned"
		end
  end

  root :to => 'homepage#index'
  get "initial_setup" => "homepage#initial_setup"

  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "homepage#new", :as => "sign_up"
	get "dashboard" => "homepage#dashboard", :as => "dashboard"
	get "blog" => "homepage#blog", :as => "blog"
	resources :accounts

  namespace :admin do
    get "homepage" => "homepage#index"
		resources :cores
		resources :rewards
    resources :supporter_levels do
    	member do
    		get "rewards"
    	end
    end
		resources :users
		resources :posts do
			member do
				post "publish"
			end
		end
  end
  resources :password_resets
end

app/models/user.rb
class User < ApplicationRecord
	enum user_type: { admin: 1, supervisor: 2, supporter: 3}

  has_secure_password

  before_create { generate_token(:auth_token) }

  belongs_to :supporter_level, optional: true
	has_many :votes, dependent: :destroy
	has_many :suggestions

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: { case_sensitive: true }
	validates :supporter_level, presence: true, if: :is_supporter?

	validates :password, presence: true, if: :should_validate_password?
	validates :password_confirmation, presence: true, if: :should_validate_password_confirmation?

	def should_validate_password?
    new_record? || password.present?
  end

	def should_validate_password_confirmation?
    new_record? || password.present?
  end

	def set_admin
		self.user_type = User.user_types[:admin]
	end

	def set_supervisor
		self.user_type = User.user_types[:supervisor]
	end

	def set_supporter
		self.user_type = User.user_types[:supporter]
	end

  def is_admin?
    self.user_type == "admin"
  end

  def is_supervisor?
    self.user_type == "supervisor"
  end

  def is_supporter?
    self.user_type == "supporter"
  end

  def full_name
    "#{first_name} #{last_name}".presence or name
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :admins_only
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
		@supporter_levels = SupporterLevel.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User added' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'Details updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    # @user.destroy
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
		redirect_to admin_users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :supporter_level_id, :allow_marketing, :user_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    unless User.all.empty? then
    	@user.user_type_id = 3
		else
			@user.user_type_id = 1
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Congratulations you are all set!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to dashboard_path, notice: 'Details updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :supporter_level_id, :allow_marketing)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, url: url, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :first_name %>
		    <%= form.text_field :first_name, class: "form-control" %>
		  </div>
		</div>
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :last_name %>
		    <%= form.text_field :last_name, class: "form-control" %>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :email %>
		    <%= form.text_field :email, placeholder: nil, class: "form-control" %>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :supporter_level_id, "Supporter Level" %>
		    <%= form.select :supporter_level_id, SupporterLevel.all.collect {|suppoter_level| [suppoter_level.name, suppoter_level.id]}, {include_blank: true}, {class: "form-control"} %>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :password %>
		    <%= form.password_field :password, class: "form-control" %>
		  </div>
		</div>
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :password_confirmation %>
		    <%= form.password_field :password_confirmation, class: "form-control" %>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :user_type, "User Type" %>
		    <%= form.select :user_type, ["admin", "supervisor", "supporter"], {}, class: "form-control" %>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
			  <%= form.check_box :allow_marketing %>
				<%= form.label :allow_marketing %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="actions">
		    <%= form.submit button_name, class: "btn btn-primary" %>
		  </div>
		</div>
	</div>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Editing User</h2>

<%= render partial: "form", locals: {user: @user, url: admin_user_path(@user), button_name: "Update"} %>

<br>

<%= link_to 'Back', :back %>

app/views/admin/users/index.html.erb
<br>
<h2>All users</h2>
<br>
<div class="row">
	<div class="col-md-12">
		<p>Please note that all details within here are protected and not to be used for any purpose other than the use intended on sign up. Please do not release any of the information outside of the app.</p>
	</div>
	<% @supporter_levels.each do |supporter_level| %>
		<div class="col-md-4 supporter-level-containers">
			<h3><%= supporter_level.name %> @ <%= number_to_currency(supporter_level.amount, :unit => "£") %></h3>
			<h4><%= supporter_level.users.count %></h4>
			Supporters at this level
			<br>
			<%= link_to 'Edit', edit_admin_supporter_level_path(supporter_level) %>
			<br>
		</div>
	<% end %>
</div>
<br>
<div class="row">
	<div class="col-md-12">
		<table class="table table-bordered table-striped">
		  <thead class="thead-dark">
		    <tr>
		      <th scope="col">First name</th>
		      <th scope="col">Last name</th>
		      <th scope="col">Email</th>
		      <th scope="col">User type</th>
					<th scope="col">Supporter level</th>
		      <th scope="col"></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @users.each do |user| %>
		      <tr>
		        <td><%= user.first_name %></td>
		        <td><%= user.last_name %></td>
		        <td><%= user.email.gsub(/.{0,4}@/, '####@') %></td>
		        <td><%= user.user_type %></td>
						<td><%= if user.supporter_level then user.supporter_level.name end %></td>
		        <td><%= link_to 'Edit', edit_admin_user_path(user), class: "btn btn-primary" %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>
<br>
<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h2>New User</h2>

<%= render partial: "form", locals: {user: @user, url: admin_users_path, button_name: "Register"} %>

<br>

<%= link_to 'Back', admin_users_path %>