config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :suggestions do
		resources :votes
  	member do
			post "completed"
			post "incomplete"
		end
		collection do
			get "all_completed"
			get "all_suggested"
			get "all_banned"
		end
  end

  root :to => 'homepage#index'
  get "initial_setup" => "homepage#initial_setup"

  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "homepage#new", :as => "sign_up"
	get "dashboard" => "homepage#dashboard", :as => "dashboard"
	get "blog" => "homepage#blog", :as => "blog"
	resources :accounts

  namespace :admin do
    get "homepage" => "homepage#index"
		resources :cores
		resources :rewards
    resources :supporter_levels do
    	member do
    		get "rewards"
    	end
    end
		resources :users
		resources :posts do
			member do
				post "publish"
			end
		end
  end
  resources :password_resets
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
	has_many :votes, dependent: :destroy
	belongs_to :user
	validates :name, :description, presence: true
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
	before_action :require_login
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy, :completed, :incomplete]

  # GET /suggestions
  # GET /suggestions.json
  def index
		@suggestions = Suggestion.where(completed: false, banned: false).order(vote_count: :desc).limit(5)
		@page_title = "Top 5 Suggestions"
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)
		@suggestion.user = current_user
		if current_user.is_admin? then
			@suggestion.admin_suggested = true
		end

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion, notice: 'Suggestion created' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion updated' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def completed
		@suggestion.completed = true
		@suggestion.save!
		redirect_to suggestions_path, notice: "Suggestion marked as completed"
	end

	def incomplete
		@suggestion.completed = false
		@suggestion.save!
		redirect_to suggestions_path, notice: "Suggestion marked as incomplete"
	end

	def all_banned
		@suggestions = Suggestion.where(completed: false, banned: true).order(created_at: :desc)
		@page_title = "Banned Suggestions"
		respond_to do |format|
        format.js
    end
	end

	def all_completed
		@suggestions = Suggestion.where(completed: true, banned: false).order(created_at: :desc)
		@page_title = "All Completed Suggestions"
		respond_to do |format|
        format.js
    end
	end

	def all_suggested
		@suggestions = Suggestion.where(completed: false, banned: false).order(created_at: :desc)
		@page_title = "All Suggestions"
		respond_to do |format|
        format.js
    end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def suggestion_params
      params.require(:suggestion).permit(:name, :description, :banned, :banned_reason)
    end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.erb
<%= form_with(model: suggestion, local: true) do |form| %>
  <% if suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
        <% suggestion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :name %>
		    <%= form.text_field :name, class: "form-control" %>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
		    <%= form.label :description %>
		    <%= form.text_area :description, class: "form-control" %>
		  </div>
		</div>
	</div>
	<% if current_user.is_admin? && @suggestion.new_record? == false %>
	<div class="row">
		<div class="col-md-3">
			<div class="field form-group">
				<%= form.label :banned %>
				<%= form.check_box :banned %>
			</div>
		</div>
	</div>
		<div class="row">
			<div class="col-md-3">
				<div class="field form-group">
			    <%= form.label :banned_reason %>
			    <%= form.text_area :banned_reason, class: "form-control" %>
			  </div>
			</div>
		</div>
	<% end %>
	<div class="row">
		<div class="col-md-3">
			<div class="actions">
		    <%= form.submit class: "btn btn-primary" %>
		  </div>
		</div>
	</div>
<% end %>

app/views/suggestions/_table.html.erb
<% if @page_title then page_title = @page_title end %>
<% if @suggestions then suggestions = @suggestions end %>
<br>
<h2><%= page_title.to_s %></h2>
<br>
<div>
	<table class="table table-bordered table-striped">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Name</th>
				<th scope="col">Description</th>
				<th scope="col">Votes</th>
				<th scope="col"></th>
				<th scope="col"></th>
				<% if current_user.is_admin? %>
					<th scope="col"></th>
				<% end %>
			</tr>
		</thead>

		<tbody>
			<% suggestions.each do |suggestion| %>
				<tr>
					<td><%= suggestion.name %></td>
					<td><%= truncate suggestion.description, length: 100, omission: '... (continued)' %></td>
					<td><%= suggestion.vote_count %> <%= (suggestion.vote_count) == 1 ? 'Vote' : 'Votes'%></td>
					<% unless current_user.is_admin? || suggestion.banned == true %>
					<% pre_vote = suggestion.votes.find { |vote| vote.user_id == current_user.id} %>
						<% if pre_vote %>
							<td><%= link_to "Down Vote", suggestion_vote_path(suggestion, pre_vote), method: :delete, class: "btn btn-danger" %></td>
						<% else %>
						  <td><%= link_to "Vote", suggestion_votes_path(suggestion), :method => :post, class: "btn btn-success" %></td>
						<% end %>
					<% end %>
					<td><%= link_to "View", suggestion_path(suggestion), class: "btn btn-info" %></td>
					<% if suggestion.user == current_user %>
						<td><%= link_to "Edit", edit_suggestion_path(suggestion), class: "btn btn-primary" %></td>
					<% end %>
					<% if current_user.is_admin? %>
						<td><%= link_to "Complete", completed_suggestion_path(suggestion), :method => :post, class: "btn btn-success" %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/suggestions/all_banned.js.erb
$("#suggestions_table").html("<%= escape_javascript(render partial: 'table', locals: { suggestions: @suggestions, page_title: @page_title } ) %>");

app/views/suggestions/all_completed.js.erb
$("#suggestions_table").html("<%= escape_javascript(render partial: 'table', locals: { suggestions: @suggestions, page_title: @page_title } ) %>");

app/views/suggestions/all_suggested.js.erb
$("#suggestions_table").html("<%= escape_javascript(render partial: 'table', locals: { suggestions: @suggestions, page_title: @page_title } ) %>");

app/views/suggestions/banned.html.erb
<h2>Banning Suggestion</h2>

<%= render 'banned_form', suggestion: @suggestion %>
<br>
<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>
<br>
<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
		<%= link_to "Top 5 Suggestions", suggestions_path, class: "nav-link", id: "nav-top-5-tab", :remote => true %>
		<%= link_to "All Suggestions", all_suggested_suggestions_path, class: "nav-link", id: "nav-all-tab", :remote => true %>
		<%= link_to "All Completed", all_completed_suggestions_path, class: "nav-link", id: "nav-completed-tab", :remote => true %>
		<%= link_to "All Banned", all_banned_suggestions_path, class: "nav-link", id: "nav-banned-tab", :remote => true %>
  </div>
</nav>

<div id="suggestions_table">
	<%= render "table", locals: { suggestions: @suggestions, page_title: @page_title } %>
</div>

<br>

<%= link_to 'New Suggestion', new_suggestion_path %>

app/views/suggestions/index.js.erb
$("#suggestions_table").html("<%= escape_javascript(render partial: 'table', locals: { suggestions: @suggestions, page_title: @page_title } ) %>");

app/views/suggestions/new.html.erb
<h1>New Suggestion</h1>

<%= render 'form', suggestion: @suggestion %>
<br>
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<br>
<div class="row">
	<div class="col-md-3">
		<h2><%= @suggestion.name %></h2>
	</div>
	<div class="col-md-3">
		This suggesiton has <%= @suggestion.vote_count %> <%= (@suggestion.vote_count) == 1 ? 'Vote' : 'Votes'%>
	</div>
</div>

<br>
<% if @suggestion.completed == true then %>
<div class="row">
	<div class="col-md-6">
		<h3>This suggestion has been completed, you can now enjoy this content!</h3>
	</div>
</div>
<% end %>
<div class="row">
	<div class="col-md-6">
		<% if @suggestion.admin_suggested == true then %>
			This suggestion was made by <%= @suggestion.user.full_name %>
		<% else %>
			This is a user created suggestion
		<% end %>
	</div>
</div>

<br>

<div class="row">
	<div class="col-md-12">
		<% if @suggestion.banned == true %>
				<h4>This suggesiton has been banned for the following reasons:</h4>
				<br>
			  <%= simple_format(@suggestion.banned_reason) %>
				<br>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= simple_format(@suggestion.description) %>
	</div>
</div>


<% if @suggestion.user = current_user then %>
	<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<% end %>
<%= link_to 'Back', :back %>