config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  resources :suggestions do
		resources :votes
  	member do
			post "completed"
			post "incomplete"
		end
		collection do
			get "all_completed"
			get "all_suggested"
			get "all_banned"
		end
  end

  root :to => 'homepage#index'
  get "initial_setup" => "homepage#initial_setup"

  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "homepage#new", :as => "sign_up"
	get "dashboard" => "homepage#dashboard", :as => "dashboard"
	get "blog" => "homepage#blog", :as => "blog"
	resources :accounts

  namespace :admin do
    get "homepage" => "homepage#index"
		resources :cores
		resources :rewards
    resources :supporter_levels do
    	member do
    		get "rewards"
    	end
    end
		resources :users
		resources :posts do
			member do
				post "publish"
			end
		end
  end
  resources :password_resets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/core.rb
class Core < ApplicationRecord
	validates :homepage_title, :homepage_content, :homepage_about, presence: true
	# validates :sm_youtube_link, presence: true, if: self.sm_youtube == true
	# validates :sm_twitter_link, presence: true, if: self.sm_twitter == true
	# validates :sm_facebook_link, presence: true, if: self.sm_facebook == true
	# validates :sm_instagram_link, presence: true, if: self.sm_instagram == true
	has_one_attached :banner
	has_one_attached :avatar
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :content, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	enum status: { pending: 0, failed: 1, paid: 2, paypal_executed: 3}
  enum payment_gateway: { stripe: 0, paypal: 1 }
  belongs_to :supporter_level
  belongs_to :user

  scope :recently_created, ->  { where(created_at: 1.minutes.ago..DateTime.now) }

  def set_paid
    self.status = Subscription.statuses[:paid]
  end

  def set_failed
    self.status = Subscription.statuses[:failed]
  end

  def set_paypal_executed
    self.status = Subscription.statuses[:paypal_executed]
  end

	def save_with_stripe_payment
    if valid?
			@user = self.user
			@supporter_level = self.supporter_level
      customer = Stripe::Customer.create(description: @user.email, plan: @supporter_level.stripe_plan_name, card: token)
      self.token = customer.id
			self.set_paid
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
	has_many :votes, dependent: :destroy
	belongs_to :user
	validates :name, :description, presence: true
end

app/models/supporter_level.rb
class SupporterLevel < ApplicationRecord
  has_many :users
	validates :name, :amount, :description, presence: true
	has_many_attached :rewards
	has_many :subscriptions
end

app/models/user.rb
class User < ApplicationRecord
	enum user_type: { admin: 1, supervisor: 2, supporter: 3}

  has_secure_password

  before_create { generate_token(:auth_token) }

  belongs_to :supporter_level, optional: true
	has_many :votes, dependent: :destroy
	has_many :suggestions

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: { case_sensitive: true }
	validates :supporter_level, presence: true, if: :is_supporter?

	validates :password, presence: true, if: :should_validate_password?
	validates :password_confirmation, presence: true, if: :should_validate_password_confirmation?

	def should_validate_password?
    new_record? || password.present?
  end

	def should_validate_password_confirmation?
    new_record? || password.present?
  end

	def set_admin
		self.user_type = User.user_types[:admin]
	end

	def set_supervisor
		self.user_type = User.user_types[:supervisor]
	end

	def set_supporter
		self.user_type = User.user_types[:supporter]
	end

  def is_admin?
    self.user_type == "admin"
  end

  def is_supervisor?
    self.user_type == "supervisor"
  end

  def is_supporter?
    self.user_type == "supporter"
  end

  def full_name
    "#{first_name} #{last_name}".presence or name
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :suggestion
  belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    unless User.all.empty? then
    	@user.user_type_id = 3
		else
			@user.user_type_id = 1
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Congratulations you are all set!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to dashboard_path, notice: 'Details updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :supporter_level_id, :allow_marketing)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_action :find_suggestion
	before_action :find_vote, only: [:destroy]

	def create
		if already_voted?
			flash[:notice] = "You can't vote more than once"
		else
			@suggestion.votes.create(user_id: current_user.id)
			@suggestion.vote_count = @suggestion.vote_count + 1
			@suggestion.save!
		end
    redirect_to suggestions_path
  end

	def destroy
	  if !(already_voted?)
	    flash[:notice] = "Cannot remove vote"
	  else
	    @vote.destroy
			@suggestion.vote_count = @suggestion.vote_count - 1
			@suggestion.save!
	  end
		redirect_back(fallback_location: suggestions_path)
	end

  private

	def find_vote
	   @vote = @suggestion.votes.find(params[:id])
	end

	def already_voted?
	  Vote.where(user_id: current_user.id, suggestion_id: params[:suggestion_id]).exists?
	end

  def find_suggestion
    @suggestion = Suggestion.find(params[:suggestion_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cores_helper.rb
module CoresHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- <a class="navbar-brand" href="#">Sym</a> -->
	<div class="container">
		<%= link_to "Sym",  root_path, class: "navbar-brand" %>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
				<% if current_user && current_user.is_supporter? %>
					<li class="nav-item">
						<%= link_to "Suggestions", suggestions_path, class: "nav-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "Blog", blog_path, class: "nav-link" %>
					</li>
				<% end %>
				<% if current_user && current_user.is_admin? %>
				<li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Supporter links
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <%= link_to "Suggestions", suggestions_path, class: "dropdown-item" %>
	          <%= link_to "Blog", blog_path, class: "dropdown-item" %>
	        </div>
	      </li>
				<li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Admin links
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<%= link_to "Supporter Levels", admin_supporter_levels_path, class: "dropdown-item" %>
	          <%= link_to "Suggestions", suggestions_path, class: "dropdown-item" %>
	          <%= link_to "Blog", admin_posts_path, class: "dropdown-item" %>
						<%= link_to "App maintenance", admin_core_path(1), class: "dropdown-item" %>
						<%= link_to "Rewards", admin_rewards_path, class: "dropdown-item" %>
						<%= link_to "Users", admin_users_path, class: "dropdown-item" %>
	        </div>
	      </li>
				<% end %>
	    </ul>
			<ul class="navbar-nav justify-content-end">
				<% if current_user %>
					<li class="navbar-text">Welcome Back <%= current_user.full_name %></li>
					<li class="nav-item"><%= link_to 'Update your details', edit_account_path(current_user), class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Log out", log_out_path, class: "nav-link" %></li>
				<% else %>
					<li class="nav-item">
						<%= link_to "Sign up", sign_up_path, class: "nav-link" %>
					</li>
					<li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          Sign In
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<div class="signup_form">
								<%= form_tag sessions_path do %>
	 						   <div class="row">
	 						     <div class="form-group col">
	 						       <%= label_tag :email %>
	 						       <%= text_field_tag :email, nil, class: "form-control" %>
	 						     </div>
	 						   </div>
	 						   <div class="row">
	 						     <div class="form-group col">
	 						       <%= label_tag :password %>
	 						       <%= password_field_tag :password, nil, class: "form-control" %>
	 						     </div>
	 						   </div>
								 <div class="row">
								 	 <div class="form-group col">
										 <%= label_tag :remember_me %>
								     <%= check_box_tag :remember_me, 1, params[:remember_me] %>
								   </div>
								 </div>
	 						   <div class="row">
	 						     <div class="actions col">
	 						       <%= submit_tag "Log in", class: "btn btn-primary btn-block" %>
	 						     </div>
	 						   </div>
	 						   <div class="row nav-link-custom-row">
									 <div class="col nav-item">
											<%= link_to "Forgotten password?", new_password_reset_path, class: "nav-link-custom" %>
						 	     </div>
	 						   </div>
	 						 <% end %>
						 </div>
		        </div>
		      </li>
				<% end %>
			</ul>
	  </div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%= render 'layouts/navbar' %>
		<% if current_page?(root_path) then %>
			<div class="row" id="banner_background">
				<div class="container">
					<%= image_tag @content.banner, class: "img-fluid", id: "banner_image" %>
				</div>
			</div>
			<div class="container">
				<div>
					<%= image_tag @content.avatar, class: "img-fluid", id: "avatar_image" %>
				</div>
			</div>

		<% end %>
		<div class="container">

			<% flash.each do |name, msg| %>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    <% end %>

	    <%= yield %>
		</div>
  </body>
</html>